### ISSUE TITLE
Issues while adding to woodpecker

### ISSUE THREAD

**Issue by MMquant** [woodpecker-appstore/log4j-payload-generator#2]
How to open the plugin in woodpecker?

![image](https://user-images.githubusercontent.com/20891620/145992347-4c2fa1de-2dba-4ac2-b609-f0fda0737ab5.png)

**Comment by c0ny1** [comment]
1. The first time you run the Woodpecker framework, a plugins directory is generated. You can place plug-ins in this directory
2. Start the framework and see the plug-in in the following TAB.

![image](https://user-images.githubusercontent.com/15975792/146016662-1262d7b3-7b33-4a7e-9206-cc227a949eb1.png)

**Comment by MMquant** [comment]
Thank you for assistance!
